export interface Stats {
    isAuthenticated: boolean;
    user: {
      id: string;
      username: string;
      email: string;
    };
    publicationStats: {
      userPub1Percent: number;
      userPub2Percent: number;
      crowdPub1Percent: number;
      crowdPub2Percent: number;
      totalRatingsCount: number;
      pub1RatingsCount: number;
      pub2RatingsCount: number;
    };
    pub_1_crowd_total_bias: number;
    pub_2_crowd_total_bias: number;
    pub_1_personal_bias: {
      publication: string;
      total_bias: number;
      sensationalism: number;
      undue_weight_bias: number;
      speculative_content: number;
      tonality_bias: number;
      concision_bias: number;
      coverage_bias: number;
      distortion_bias: number;
      partisan_bias: number;
      favors_or_attacks: number;
      content_bias: number;
      structural_bias: number;
      gatekeeping_bias: number;
      decision_making_bias: number;
      mainstream_bias: number;
      false_balance_bias: number;
    };
    pub_2_personal_bias: {
      publication: string;
      total_bias: number;
      sensationalism: number;
      undue_weight_bias: number;
      speculative_content: number;
      tonality_bias: number;
      concision_bias: number;
      coverage_bias: number;
      distortion_bias: number;
      partisan_bias: number;
      favors_or_attacks: number;
      content_bias: number;
      structural_bias: number;
      gatekeeping_bias: number;
      decision_making_bias: number;
      mainstream_bias: number;
      false_balance_bias: number;
    };
    pub_1_crowd_bias: {
      publication: string;
      total_bias: number;
      sensationalism: number;
      undue_weight_bias: number;
      speculative_content: number;
      tonality_bias: number;
      concision_bias: number;
      coverage_bias: number;
      distortion_bias: number;
      partisan_bias: number;
      favors_or_attacks: number;
      content_bias: number;
      structural_bias: number;
      gatekeeping_bias: number;
      decision_making_bias: number;
      mainstream_bias: number;
      false_balance_bias: number;
    };
    pub_2_crowd_bias: {
      publication: string;
      total_bias: number;
      sensationalism: number;
      undue_weight_bias: number;
      speculative_content: number;
      tonality_bias: number;
      concision_bias: number;
      coverage_bias: number;
      distortion_bias: number;
      partisan_bias: number;
      favors_or_attacks: number;
      content_bias: number;
      structural_bias: number;
      gatekeeping_bias: number;
      decision_making_bias: number;
      mainstream_bias: number;
      false_balance_bias: number;
    };
  }

  export let initialStats = <Stats>{
    isAuthenticated: false,
    user: {
      id: "",
      username: "",
      email: "",
    },
    publicationStats: {
      userPub1Percent: 0,
      userPub2Percent: 0,
      crowdPub1Percent: 0,
      crowdPub2Percent: 0,
      totalRatingsCount: 0,
      pub1RatingsCount: 0,
      pub2RatingsCount: 0,
    },
    pub_1_crowd_total_bias: 0,
    pub_2_crowd_total_bias: 0,
    pub_1_personal_bias: {
      publication: "",
      total_bias: 0,
      sensationalism: 0,
      undue_weight_bias: 0,
      speculative_content: 0,
      tonality_bias: 0,
      concision_bias: 0,
      coverage_bias: 0,
      distortion_bias: 0,
      partisan_bias: 0,
      favors_or_attacks: 0,
      content_bias: 0,
      structural_bias: 0,
      gatekeeping_bias: 0,
      decision_making_bias: 0,
      mainstream_bias: 0,
      false_balance_bias: 0,
    },
    pub_2_personal_bias: {
      publication: "",
      total_bias: 0,
      sensationalism: 0,
      undue_weight_bias: 0,
      speculative_content: 0,
      tonality_bias: 0,
      concision_bias: 0,
      coverage_bias: 0,
      distortion_bias: 0,
      partisan_bias: 0,
      favors_or_attacks: 0,
      content_bias: 0,
      structural_bias: 0,
      gatekeeping_bias: 0,
      decision_making_bias: 0,
      mainstream_bias: 0,
      false_balance_bias: 0,
    },
    pub_1_crowd_bias: {
      publication: "",
      total_bias: 0,
      sensationalism: 0,
      undue_weight_bias: 0,
      speculative_content: 0,
      tonality_bias: 0,
      concision_bias: 0,
      coverage_bias: 0,
      distortion_bias: 0,
      partisan_bias: 0,
      favors_or_attacks: 0,
      content_bias: 0,
      structural_bias: 0,
      gatekeeping_bias: 0,
      decision_making_bias: 0,
      mainstream_bias: 0,
      false_balance_bias: 0,
    },
    pub_2_crowd_bias: {
      publication: "",
      total_bias: 0,
      sensationalism: 0,
      undue_weight_bias: 0,
      speculative_content: 0,
      tonality_bias: 0,
      concision_bias: 0,
      coverage_bias: 0,
      distortion_bias: 0,
      partisan_bias: 0,
      favors_or_attacks: 0,
      content_bias: 0,
      structural_bias: 0,
      gatekeeping_bias: 0,
      decision_making_bias: 0,
      mainstream_bias: 0,
      false_balance_bias: 0,
    },
  }